### ISSUE TITLE
Api for the plugin

### ISSUE THREAD

**Issue by CodeDoctorDE** [PhilipFlyvholm/CustomCobbleGen#25]
Hello, I'm the creator of ItemMods where you can create your own blocks. I want to make support for your plugin and I need an api where I can implement it.

Sincerely,
CodeDoctor

https://songoda.com/marketplace/product/itemmods-your-itemblock-modification-plugin-itemmods.162

**Comment by phil14052** [comment]
This has also been added to the todo list

**Comment by phil14052** [comment]
Hi @CodeDoctorDE 
I have added the first version of the API in version 1.4.1
Could you have a look at it? I am more than willing to add more stuff to the API if you need more functions and events!
