### ISSUE TITLE
Enchantment name returning null

### ISSUE THREAD

**Issue by ShaneBeee** [PhilipFlyvholm/CustomCobbleGen#42]
**Describe the bug**
So I'm the dev of HungerGames. 
A user was reporting an issue with enchants in the config, throwing an NPE.
After spending the last hour trying to find the issue, I figured out it come from this plugin.

In my plugin, I'm looping the list of enchants and getting the keys and names, allowing users to use the Minecraft keys as well as the silly Bukkit names.
Yes yes I know... the getName method IS deprecated and I shouldn't use it, but here is what I noticed:
https://github.com/phil14052/CustomCobbleGen/blob/d3f05bb507cdc49c83a0b0f0ad5280e970445b07/src/me/phil14052/CustomCobbleGen/Utils/GlowEnchant.java#L41-L44

According to Bukkit's code:
```java
    @NotNull
    @Deprecated
    public abstract String getName();
```
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/enchantments/Enchantment.java#231
this is NotNull, so the name should NOT return null.

**To Reproduce**
I don't really have steps, just see above.

**Expected behavior**
The name SHOULD return the name.

**Console errors**
I don't have any from this plugin specifically.

**Config file**
null

**Screenshots**
nill

**System (please complete the following information):**
NULL (the error was brought up from a member on my discord)

**Additional context**

**Comment by phil14052** [comment]
Hi, I will make a fix for this.
